Sec13
saganoH/Swift_study pull request #26
Opened 2020-11-17 01:10 UTC by saganoH

https://trello.com/c/OnPbKdEs/74-8-%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E5%AD%A6%E7%BF%9213%E7%AB%A0

ナビゲーションコントローラーすぐできそうだったので追加しました

2020-11-17 02:03 UTC, TakahiroAnamizu requested changes

2020-11-17 02:03 UTC, ghost commented on SwiftStudy/SwiftStudy/Sec13ViewController5.swift
> +    //UITableViewDelegateメソッド
L49とL50の間に改行を入れましょう

2020-11-17 02:03 UTC, ghost commented on SwiftStudy/SwiftStudy/Sec13ViewController2.swift
> +
不要な改行を削除すると、よりリーダブルなコードになるので、意識してみてください

2020-11-17 02:03 UTC, ghost commented on SwiftStudy/SwiftStudy/Sec13ViewController5.swift
> +let sectionTitle = ["チョウ目", "バッタ目", "コウチュウ目"]
これらのプロパティはこのVCでしか使わないのであれば、VC内で定義するようにしましょう
ここで宣言してしまうと、どこからでもアクセス可能なので、保守性の悪いコードとなってしまいます

2020-11-17 02:03 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Sec13ViewController5.swift
> +let sectionTitle = ["チョウ目", "バッタ目", "コウチュウ目"]
さらに応用として、`Sec13ViewController5 .section0`など、外部から参照する必要がなければ`private`にしましょう
こちらも、不要な参照を避けることで保守性の向上に寄与します

2020-11-17 02:03 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Sec13ViewController5.swift
> +    //UITableViewDelegateメソッド
そして今更すぎる指摘になりますが、`// コメント`と`//`の後にスペースを入れるようにしましょう

2020-11-17 04:45 UTC, saganoH commented on SwiftStudy/SwiftStudy/Sec13ViewController5.swift
> +let sectionTitle = ["チョウ目", "バッタ目", "コウチュウ目"]
デリゲートの追加学習時に修正した方が良さそう
![スクリーンショット 2020-11-17 13 39 37](https://user-images.githubusercontent.com/69957710/99347517-ab7cda80-28da-11eb-8022-10635002aefa.png)

単純にクラス内に移す→tableDataがエラーに
viewDidLoadないに移す→プロトコルとデリゲートメソッドから参照できなくなる

2020-11-18 02:27 UTC, TakahiroAnamizu approved these changes

2020-11-18 02:27 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Sec13ViewController5.swift
>      // UITableViewDataSourseプロトコル
`// MARK: - UITableViewSource`のように書くと区切りとして判別しやすくなります

2020-11-18 02:27 UTC, merged