Sec15
saganoH/Swift_study pull request #29
Opened 2020-11-30 06:58 UTC by saganoH

https://trello.com/c/NzGtD4bq/90-5-%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E5%AD%A6%E7%BF%9215%E7%AB%A0-05

2020-11-30 07:54 UTC, TakahiroAnamizu requested changes
学習コードなので指摘はしませんが、リーダブルコード的には無駄なコメントは避けたいので、理解してるものは省くようにしましょう

2020-11-30 07:54 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter15/Sec15ViewController.swift
> +        Timer.scheduledTimer(
画面読み込みで必須でない処理は、基本的にViewWillAppearなど表示前に実行するようにしましょう
ユーザは、画面遷移の操作をしたときに待たされるとストレスになる傾向があり、アプリの使い勝手に影響が出てきます

2020-11-30 07:54 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter15/Sec15ViewController.swift
> +        Timer.scheduledTimer(
ScrollViewなど遷移が重い画面があったと思うので、試してみると違いがわかりやすいかも

2020-11-30 07:55 UTC, TakahiroAnamizu requested changes

2020-11-30 07:55 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter15/Sec15ViewController4.swift
> +        // スライダの範囲を決める
ここもviewWillAppearなどに移す検討を

2020-12-01 00:29 UTC, saganoH commented on SwiftStudy/SwiftStudy/Chapter15/Sec15ViewController.swift
> +        Timer.scheduledTimer(
ここの判断難しいですね、、、

2020-12-01 01:49 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter15/Sec15ViewController.swift
> +        Timer.scheduledTimer(
基本的な事前処理は`viewWillAppear`、事前読み込みが必要かつ重い処理は`viewDidLoad`くらいのスタンスで良いと思います

2020-12-01 02:07 UTC, TakahiroAnamizu commented
### 応用的な書き方をコミットしました
* `didSet`を用いた`View`のパラメータ設定の方法
* 早期リターンを用いたネストの改善
### バグ？の修正
* タップで花弁の表示の際、ボタンが隠れる問題
* アニメーション速度を変更するウサギ画面の、初期表示がない問題

2020-12-01 02:12 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter15/Sec15ViewController4.swift
> +        didSet {
一度だけ設定するようなプロパティなどは、このように書くと関連が一目で分かるので可読性に繋がります

2020-12-01 02:12 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter15/Sec15ViewController4.swift
> +            usagiView.image = UIImage(named: "slow")
初期表示がない理由は、設定時に画像がセットされてなかったため

2020-12-01 02:12 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter15/Sec15ViewController4.swift
>          if sender.value == 0 {
早期リターンすることで、0以外の時のコードのネストが浅くなり可読性の向上に繋がります

2020-12-01 02:12 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter15/Sec15ViewController3.swift
> +        view.sendSubviewToBack(flower)
最前面煮出したいときは`view.bringSubviewToFront(view: UIView)`を用います
合わせて覚えておくと良いと思います

2020-12-01 02:33 UTC, TakahiroAnamizu approved these changes

2020-12-01 02:33 UTC, merged