Sec18
saganoH/Swift_study pull request #31
Opened 2020-12-04 06:42 UTC by saganoH

https://trello.com/c/r4FqIZ7R/106-5-%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E5%AD%A6%E7%BF%9218%E7%AB%A0

2020-12-04 07:36 UTC, saganoH commented
月曜修正すべきところ

* キーボードが閉じたらテキストを消す
* タップしたら閉じるようにする
* 灰色背景で戻るボタンが無効化されているように見える現象の改善
* 強制アンラップしているところ

2020-12-07 05:25 UTC, TakahiroAnamizu requested changes
クラス化できるロジックがないか検討してみてください
これらが"何"を中核に据えたロジックなのか考えると見えてくるかもしれませんね

2020-12-07 05:25 UTC, ghost commented on SwiftStudy/SwiftStudy/Chapter18/Sec18ViewController3.swift
> +        textView1.text = ""
この処理の場合、`textView1`で書いた後、保存を押さず`textView2`をタップしても消えてしまいます
初期文字列をプロパティ保持しておいて、`textView.text`が一致したら空にする、とか分岐処理が必要ですね
(それでも初期値のまま`textView2`をタップすると消えてしまいますが)

2020-12-07 05:25 UTC, ghost commented on SwiftStudy/SwiftStudy/Chapter18/Sec18ViewController4.swift
> +        }
ここをまとめて書くとこうなります
まとめて書くかはケースバイケースになることもありますが、基本的に処理内容が同じ場合はまとめて良いと思います
```
guard let userInfo = (notification as NSNotification).userInfo,
              let nsClass = (userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue) else {
           return
        }
```

2020-12-08 04:49 UTC, saganoH commented
パスを分けて指定しましたが、sec18vc4は読み込みから始まるため、読み込めるファイルがないとエラーになることに気がついたので、パスの指定を同じにしました

2020-12-08 04:54 UTC, TakahiroAnamizu requested changes

2020-12-08 04:54 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter18/Sec18ViewController3.swift
> +class FileOperator {
ファイルを分けましょう

2020-12-08 04:54 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/Chapter18/Sec18ViewController3.swift
> +    private let firstText = "文字を入力してください"
@IBOutlet の下に移しましょう

2020-12-08 05:06 UTC, TakahiroAnamizu approved these changes

2020-12-08 05:06 UTC, merged