sec2-5
saganoH/Swift_study pull request #4
Opened 2020-10-07 06:17 UTC by saganoH

if文

2020-10-07 06:19 UTC, saganoH commented
https://trello.com/c/zAdi91pk/33-5-swift%E5%AD%A6%E7%BF%922-2%E7%AB%A0

2020-10-07 06:28 UTC, TakahiroAnamizu requested changes

2020-10-07 06:28 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/ViewController.swift
> -        print(rangeInt.contains(value))
せっかく作ったコード消しちゃうのはもったいないので、復活させましょうか

2020-10-07 06:28 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/ViewController.swift
> -        print(rangeDouble.contains(value))
こちらも復活

2020-10-07 06:28 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/ViewController.swift
> -        view.backgroundColor = UIColor(red:R, green:G, blue:B, alpha:1)
こちらも復活

2020-10-07 06:28 UTC, TakahiroAnamizu commented on SwiftStudy/SwiftStudy/ViewController.swift
> +        ifStatement()
これらの関数を外から乱数を渡すように変更してみましょうか

2020-10-08 01:20 UTC, TakahiroAnamizu approved these changes

2020-10-08 01:20 UTC, merged